/*
 * robolaunch Industry Cloud Platform - OpenAPI 3.0
 *
 * API for robolaunch ICP platform structure.
 *
 * API version: 1.0.11
 * Contact: info@robolaunch.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/v3/",
		Index,
	},

	Route{
		"GetPlatformComponents",
		strings.ToUpper("Get"),
		"/api/v3/components",
		GetPlatformComponents,
	},

	Route{
		"GetVersionedPlatformPlaneComponents",
		strings.ToUpper("Get"),
		"/api/v3/components/{version}/{plane}",
		GetVersionedPlatformPlaneComponents,
	},

	Route{
		"GetEnvironment",
		strings.ToUpper("Get"),
		"/api/v3/environments/{version}/{domain}/environment",
		GetEnvironment,
	},

	Route{
		"GetEnvironmentsOfDomain",
		strings.ToUpper("Get"),
		"/api/v3/environments/{version}/{domain}",
		GetEnvironmentsOfDomain,
	},

	Route{
		"GetPlatformImages",
		strings.ToUpper("Get"),
		"/api/v3/environments",
		GetPlatformImages,
	},

	Route{
		"GetVersionedPlatformImages",
		strings.ToUpper("Get"),
		"/api/v3/environments/{version}",
		GetVersionedPlatformImages,
	},

	Route{
		"GetPlatform",
		strings.ToUpper("Get"),
		"/api/v3/platform",
		GetPlatform,
	},
}
