versions:
  0.1.2-prerelease.10:
    organization: robolaunchio
    repository: devspace
    domains:
      tools:
        alias: "Tools"
        description: "Sample Description"
        environments:
        - application:
            name: code-editor
            version: "4.22.0"
            alias: "Code Editor"
            description: "Code editor for cloud environments."
            icon: "https://raw.githubusercontent.com/robolaunch/trademark/main/applications/code-editor-logo.png"
          base:
            ubuntu: jammy
            desktop: xfce
            version: "0.2.6-alpha.19"
        - application:
            name: edge-proxy
            version: "1.7.4.1-3ubuntu4"
            alias: "Edge Proxy"
            description: "Edge proxy relays services bi-directionally."
            icon: "https://raw.githubusercontent.com/robolaunch/trademark/main/applications/edge-proxy-logo.png"
          base:
            ubuntu: jammy
            desktop: xfce
            version: "0.2.6-alpha.20"