/*
 * robolaunch Industry Cloud Platform - OpenAPI 3.0
 *
 * API for robolaunch ICP platform structure.
 *
 * API version: 1.0.11
 * Contact: info@robolaunch.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type Component struct {
	Name string `json:"name"`

	Tag string `json:"tag"`

	Repository string `json:"repository"`

	Docs string `json:"docs"`

	Release string `json:"release"`

	Helm *HelmChart `json:"helm,omitempty"`

	Resources map[string]string `json:"resources,omitempty"`
}
