/*
 * robolaunch Industry Cloud Platform - OpenAPI 3.0
 *
 * API for robolaunch ICP platform structure.
 *
 * API version: 1.0.11
 * Contact: info@robolaunch.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type Robolaunch struct {
	Platform string `json:"platform"`

	Contact map[string]string `json:"contact"`

	Maintainers []string `json:"maintainers"`

	Versions []VersionMeta `json:"versions"`
}
